package com.xinrui.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xinrui.smart.pojo.DeviceHome;
import com.xinrui.smart.pojo.RoomEntry;
import com.xinrui.smart.pojo.TaskTime;

import com.xinrui.database.dao.DeviceHomeDao;
import com.xinrui.database.dao.RoomEntryDao;
import com.xinrui.database.dao.TaskTimeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceHomeDaoConfig;
    private final DaoConfig roomEntryDaoConfig;
    private final DaoConfig taskTimeDaoConfig;

    private final DeviceHomeDao deviceHomeDao;
    private final RoomEntryDao roomEntryDao;
    private final TaskTimeDao taskTimeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceHomeDaoConfig = daoConfigMap.get(DeviceHomeDao.class).clone();
        deviceHomeDaoConfig.initIdentityScope(type);

        roomEntryDaoConfig = daoConfigMap.get(RoomEntryDao.class).clone();
        roomEntryDaoConfig.initIdentityScope(type);

        taskTimeDaoConfig = daoConfigMap.get(TaskTimeDao.class).clone();
        taskTimeDaoConfig.initIdentityScope(type);

        deviceHomeDao = new DeviceHomeDao(deviceHomeDaoConfig, this);
        roomEntryDao = new RoomEntryDao(roomEntryDaoConfig, this);
        taskTimeDao = new TaskTimeDao(taskTimeDaoConfig, this);

        registerDao(DeviceHome.class, deviceHomeDao);
        registerDao(RoomEntry.class, roomEntryDao);
        registerDao(TaskTime.class, taskTimeDao);
    }
    
    public void clear() {
        deviceHomeDaoConfig.clearIdentityScope();
        roomEntryDaoConfig.clearIdentityScope();
        taskTimeDaoConfig.clearIdentityScope();
    }

    public DeviceHomeDao getDeviceHomeDao() {
        return deviceHomeDao;
    }

    public RoomEntryDao getRoomEntryDao() {
        return roomEntryDao;
    }

    public TaskTimeDao getTaskTimeDao() {
        return taskTimeDao;
    }

}
