package com.xinrui.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xinrui.secen.scene_pojo.RoomEntry;
import com.xinrui.smart.pojo.DeviceChild;
import com.xinrui.smart.pojo.DeviceGroup;
import com.xinrui.smart.pojo.TimeTask;
import com.xinrui.smart.pojo.Timer;

import com.xinrui.database.dao.RoomEntryDao;
import com.xinrui.database.dao.DeviceChildDao;
import com.xinrui.database.dao.DeviceGroupDao;
import com.xinrui.database.dao.TimeTaskDao;
import com.xinrui.database.dao.TimerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig roomEntryDaoConfig;
    private final DaoConfig deviceChildDaoConfig;
    private final DaoConfig deviceGroupDaoConfig;
    private final DaoConfig timeTaskDaoConfig;
    private final DaoConfig timerDaoConfig;

    private final RoomEntryDao roomEntryDao;
    private final DeviceChildDao deviceChildDao;
    private final DeviceGroupDao deviceGroupDao;
    private final TimeTaskDao timeTaskDao;
    private final TimerDao timerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        roomEntryDaoConfig = daoConfigMap.get(RoomEntryDao.class).clone();
        roomEntryDaoConfig.initIdentityScope(type);

        deviceChildDaoConfig = daoConfigMap.get(DeviceChildDao.class).clone();
        deviceChildDaoConfig.initIdentityScope(type);

        deviceGroupDaoConfig = daoConfigMap.get(DeviceGroupDao.class).clone();
        deviceGroupDaoConfig.initIdentityScope(type);

        timeTaskDaoConfig = daoConfigMap.get(TimeTaskDao.class).clone();
        timeTaskDaoConfig.initIdentityScope(type);

        timerDaoConfig = daoConfigMap.get(TimerDao.class).clone();
        timerDaoConfig.initIdentityScope(type);

        roomEntryDao = new RoomEntryDao(roomEntryDaoConfig, this);
        deviceChildDao = new DeviceChildDao(deviceChildDaoConfig, this);
        deviceGroupDao = new DeviceGroupDao(deviceGroupDaoConfig, this);
        timeTaskDao = new TimeTaskDao(timeTaskDaoConfig, this);
        timerDao = new TimerDao(timerDaoConfig, this);

        registerDao(RoomEntry.class, roomEntryDao);
        registerDao(DeviceChild.class, deviceChildDao);
        registerDao(DeviceGroup.class, deviceGroupDao);
        registerDao(TimeTask.class, timeTaskDao);
        registerDao(Timer.class, timerDao);
    }
    
    public void clear() {
        roomEntryDaoConfig.clearIdentityScope();
        deviceChildDaoConfig.clearIdentityScope();
        deviceGroupDaoConfig.clearIdentityScope();
        timeTaskDaoConfig.clearIdentityScope();
        timerDaoConfig.clearIdentityScope();
    }

    public RoomEntryDao getRoomEntryDao() {
        return roomEntryDao;
    }

    public DeviceChildDao getDeviceChildDao() {
        return deviceChildDao;
    }

    public DeviceGroupDao getDeviceGroupDao() {
        return deviceGroupDao;
    }

    public TimeTaskDao getTimeTaskDao() {
        return timeTaskDao;
    }

    public TimerDao getTimerDao() {
        return timerDao;
    }

}
