package com.xinrui.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xinrui.smart.pojo.TaskTime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK_TIME".
*/
public class TaskTimeDao extends AbstractDao<TaskTime, Long> {

    public static final String TABLENAME = "TASK_TIME";

    /**
     * Properties of entity TaskTime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Start = new Property(1, int.class, "start", false, "START");
        public final static Property End = new Property(2, int.class, "end", false, "END");
        public final static Property Temp = new Property(3, int.class, "temp", false, "TEMP");
        public final static Property DeviceId = new Property(4, long.class, "deviceId", false, "DEVICE_ID");
        public final static Property Week = new Property(5, String.class, "week", false, "WEEK");
    }


    public TaskTimeDao(DaoConfig config) {
        super(config);
    }
    
    public TaskTimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK_TIME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"START\" INTEGER NOT NULL ," + // 1: start
                "\"END\" INTEGER NOT NULL ," + // 2: end
                "\"TEMP\" INTEGER NOT NULL ," + // 3: temp
                "\"DEVICE_ID\" INTEGER NOT NULL ," + // 4: deviceId
                "\"WEEK\" TEXT);"); // 5: week
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_TIME\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TaskTime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStart());
        stmt.bindLong(3, entity.getEnd());
        stmt.bindLong(4, entity.getTemp());
        stmt.bindLong(5, entity.getDeviceId());
 
        String week = entity.getWeek();
        if (week != null) {
            stmt.bindString(6, week);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TaskTime entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStart());
        stmt.bindLong(3, entity.getEnd());
        stmt.bindLong(4, entity.getTemp());
        stmt.bindLong(5, entity.getDeviceId());
 
        String week = entity.getWeek();
        if (week != null) {
            stmt.bindString(6, week);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TaskTime readEntity(Cursor cursor, int offset) {
        TaskTime entity = new TaskTime( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // start
            cursor.getInt(offset + 2), // end
            cursor.getInt(offset + 3), // temp
            cursor.getLong(offset + 4), // deviceId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // week
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TaskTime entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStart(cursor.getInt(offset + 1));
        entity.setEnd(cursor.getInt(offset + 2));
        entity.setTemp(cursor.getInt(offset + 3));
        entity.setDeviceId(cursor.getLong(offset + 4));
        entity.setWeek(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TaskTime entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TaskTime entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TaskTime entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
