package com.xinrui.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xinrui.smart.pojo.Timer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIMER".
*/
public class TimerDao extends AbstractDao<Timer, Long> {

    public static final String TABLENAME = "TIMER";

    /**
     * Properties of entity Timer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeviceId = new Property(1, long.class, "deviceId", false, "DEVICE_ID");
        public final static Property Week = new Property(2, int.class, "week", false, "WEEK");
        public final static Property Temp = new Property(3, int.class, "temp", false, "TEMP");
        public final static Property Open = new Property(4, String.class, "open", false, "OPEN");
        public final static Property Hour = new Property(5, int.class, "hour", false, "HOUR");
    }


    public TimerDao(DaoConfig config) {
        super(config);
    }
    
    public TimerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TIMER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DEVICE_ID\" INTEGER NOT NULL ," + // 1: deviceId
                "\"WEEK\" INTEGER NOT NULL ," + // 2: week
                "\"TEMP\" INTEGER NOT NULL ," + // 3: temp
                "\"OPEN\" TEXT," + // 4: open
                "\"HOUR\" INTEGER NOT NULL );"); // 5: hour
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TIMER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Timer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDeviceId());
        stmt.bindLong(3, entity.getWeek());
        stmt.bindLong(4, entity.getTemp());
 
        String open = entity.getOpen();
        if (open != null) {
            stmt.bindString(5, open);
        }
        stmt.bindLong(6, entity.getHour());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Timer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDeviceId());
        stmt.bindLong(3, entity.getWeek());
        stmt.bindLong(4, entity.getTemp());
 
        String open = entity.getOpen();
        if (open != null) {
            stmt.bindString(5, open);
        }
        stmt.bindLong(6, entity.getHour());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Timer readEntity(Cursor cursor, int offset) {
        Timer entity = new Timer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // deviceId
            cursor.getInt(offset + 2), // week
            cursor.getInt(offset + 3), // temp
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // open
            cursor.getInt(offset + 5) // hour
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Timer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceId(cursor.getLong(offset + 1));
        entity.setWeek(cursor.getInt(offset + 2));
        entity.setTemp(cursor.getInt(offset + 3));
        entity.setOpen(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHour(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Timer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Timer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Timer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
